salesforce:
  a_short_running_collection_dags:
    quip:
      - metrics
      - page_views
      - permissions
      - system
      - user
    slack:
      - metrics
      - page_views
      - system
      - user
    tableau:
      - metrics
      - page_views
  a_long_running_collection_dags:
    quip:
      - java_logs
      - linux_logs
    slack:
      - java_logs
      - linux_logs
    tableau:
      - python_logs
